### ISSUE TITLE
To do

### ISSUE THREAD

**Issue by xrkffgg** [zoo-js/zoo-issue-helper#10]
- [x] 统一输入框颜色 https://github.com/zoo-js/zoo-issue-helper/pull/17
- [ ] 优化项目体积
- [ ] 优化图片加载

**Comment by xrkffgg** [comment]
- [ ] Vue3

**Comment by xrkffgg** [comment]
~~pages 自动部署~~

`"docs:deploy": "gh-pages -d docs-dist"`

**Comment by ajuner** [comment]
> * [ ]  Vue3

要不要开个vue3的分支  我给你改下放上去

**Comment by xrkffgg** [comment]
刚开始图方便，我是全量引入了 quasar，不知道这个支持 v3 了没

**Comment by xrkffgg** [comment]
https://github.com/zoo-js/zoo-issue-helper/tree/v3

**Comment by ajuner** [comment]
好像是还没有
话说回来
能开这样的一个库的人一定超可爱哈哈哈

**Comment by xrkffgg** [comment]
😅😅

**Comment by xrkffgg** [comment]
预览 PR 变更
- [x] surge preview https://github.com/afc163/surge-preview
- [ ] https://github.com/apps/vercel

**Comment by xrkffgg** [comment]
有时间的话，可以看看这个项目有啥优化的地方，UI 库也可以精简一下，单个引入。
