### ISSUE TITLE
固定 love

### ISSUE THREAD

**Issue by xrkffgg** [zoo-js/zoo-issue-helper#58]
- 新加了6个 推一下

![image](https://user-images.githubusercontent.com/29775873/99969106-fca63600-2dd4-11eb-8eae-0acc79fe8337.png)

- 放在这个地方，可以加一个粉色边框突出下，或者底色换成其他颜色 ，或者 box-shadow 颜色调整一下
- 与下面的有稍微一些间隔，同时下面的 card list 过滤这6个

- 6个顺序按照 
https://github.com/zoo-js/zoo
![image](https://user-images.githubusercontent.com/29775873/99969175-147dba00-2dd5-11eb-9724-e10e87839a0f.png)

- 注意屏幕缩小时，样式不异常

**Comment by xrkffgg** [comment]
不着急 有空再搞

**Comment by xrkffgg** [comment]
https://github.com/zoo-js/zoo-data/blob/d974c5cae125cd3b3c354a43027315b5b74fdb94/json/organizations.json#L749

这个字段看需要用

**Comment by ajuner** [comment]
就是在原本的这块上面加一块突出一点的
放这6个吧

**Comment by xrkffgg** [comment]
yes

**Comment by xrkffgg** [comment]
回头顺序我在数据里排一下吧，又加了个 css

**Comment by xrkffgg** [comment]
为了不显得 首页太空，你不用按照 zoo Readme 的顺序，可以按照

https://github.com/zoo-js/zoo-data#type

这个的，排序的说明 看下 zoo 就明白了
