### ISSUE TITLE
Bug: Regex can't match email's address includes '-' character

### ISSUE THREAD

**Issue by jiweiyuan** [zoo-js/zoo-issue-helper#74]
![image](https://user-images.githubusercontent.com/23147684/119349018-34346300-bcd0-11eb-95e8-ed0555c586ea.png)

I input a email "ji-weiyuan@outlook.com" , But I found, the Regex can't match, I guess this Regex maybe has some error.

**Comment by xrkffgg** [comment]
还有 @ 后也会出现  - 的情况， @ajuner  你的正则 要更新了

**Comment by xrkffgg** [comment]
不过 他图上报错 是因为 没选 pets ，前面的 - 感觉应该满足的
